AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: >
  Template to deploy AWS Lambda function with code in src

Parameters:
  debugMODE:
    Description: Do you want to enable logging.
    Default: "False"
    Type: String
    AllowedValues: ["True", "False"]
    ConstraintDescription: Must be boolean.
  FunctionNameSuffix:
    Description: 'Suffix to append to the Lambda functions.'
    Type: 'String'
    Default: 'Mystique'

Globals:
  Function:
    Runtime: python3.7
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        DEBUG_MODE:
          Ref: debugMODE

Resources:

  loginLambdaFn:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'AWS Lambda to get Cognito Tokens'
      FunctionName: !Sub 'loginLambdaFn-${FunctionNameSuffix}'
      Handler: login.lambda_handler
      CodeUri: ./src/app/
      Events:
        loginProxy:
          Type: Api
          Properties:
            Path: /api/login
            Method: POST
      # Events:
      #   loginProxy:
      #     Type: Api
      #     Properties:
      #       Path: /{proxy+}
      #       Method: ANY
      Policies: 
        - AWSLambdaExecute # Managed Policy
  
Outputs:
  loginLambdaFnArn:
    Description: Login Lambda ARM
    Value: !GetAtt loginLambdaFn.Arn

   